apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      run: user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: user
    spec:
      containers:
      - image: ricardomaximino/user
        name: user
        ports:
        - containerPort: 8080
        resources: {}
status: {}
