apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: user
  name: user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: user
  type: LoadBalancer
status:
  loadBalancer: {}
